FileVersion = 1
LastConfig = "Debug"
LastPlatform = "Win64"
RecentFilesList = ["src\\FileUtils.bf", "src\\BeefGenerator.bf", "src\\ILangGenerator.bf", "src\\CParser.bf", "src\\Program.bf", "src\\Extensions.bf", "Disassembly", "Disassembly", "c:\\Program Files\\BeefLang\\BeefLibs\\corlib\\src\\Variant.bf", "c:\\Program Files\\BeefLang\\BeefLibs\\corlib\\src\\String.bf"]

[MainWindow]
X = 3215
Y = 188
Width = 500
Height = 470
ShowKind = "ShowMaximized"

[MainDockingFrame]
Type = "DockingFrame"
SplitType = 2

[[MainDockingFrame.DockedWidgets]]
RequestedWidth = 350.0
RequestedHeight = 200.0
SizePriority = 200.0
Type = "DockingFrame"
SplitType = 1

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
RequestedWidth = 200.0
RequestedHeight = 200.0
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Workspace"
TabWidth = 115.0
TabIsPinned = false
Type = "ProjectPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
IsFillWidget = true
Permanent = true
RequestedWidth = 150.0
RequestedHeight = 150.0
SizePriority = 150.0
DefaultDocumentsTabbedView = true
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "FileUtils.bf"
TabWidth = 99.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\FileUtils.bf"
CursorPos = 1036
VertPos = 322.0
ProjectName = "HushBindingGen"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "BeefGenerator.bf"
TabWidth = 138.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\BeefGenerator.bf"
CursorPos = 9361
VertPos = 5405.0
ProjectName = "HushBindingGen"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "ILangGenerator.bf"
TabWidth = 144.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\ILangGenerator.bf"
ProjectName = "HushBindingGen"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Disassembly"
TabWidth = 122.0
TabIsPinned = false
Type = "DisassemblyPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "String.bf"
TabWidth = 79.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "c:\\Program Files\\BeefLang\\BeefLibs\\corlib\\src\\String.bf"
CursorPos = 95964
ProjectName = "corlib"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "CParser.bf"
TabWidth = 89.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\CParser.bf"
CursorPos = 5861
VertPos = 8027.0
ProjectName = "HushBindingGen"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Extensions.bf"
TabWidth = 106.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Extensions.bf"
CursorPos = 247
ProjectName = "HushBindingGen"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Program.bf"
TabWidth = 96.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Program.bf"
CursorPos = 766
VertPos = 1831.375
ProjectName = "HushBindingGen"

[[MainDockingFrame.DockedWidgets]]
RequestedWidth = 250.0
RequestedHeight = 254.0
Type = "DockingFrame"
SplitType = 1

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
RequestedWidth = 250.0
RequestedHeight = 250.0
SizePriority = 1272.0
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Memory"
TabWidth = 99.0
TabIsPinned = false
Type = "MemoryPanel"
AutoResize = "Auto_Mul8"
RequestedWidth = 300.0

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Watch"
TabWidth = 86.0
TabIsPinned = false
Type = "WatchPanel"
Columns = [{Width = 200.0}, {Width = 200.0}, {Width = 200.0}]

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs.Items]]
EvalStr = ""

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Auto"
TabWidth = 77.0
TabIsPinned = false
Type = "AutoWatchPanel"
Columns = [{Width = 200.0}, {Width = 200.0}, {Width = 200.0}]

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
RequestedWidth = 250.0
RequestedHeight = 250.0
SizePriority = 1272.0
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Threads"
TabWidth = 97.0
TabIsPinned = false
Type = "ThreadPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Call Stack"
TabWidth = 105.0
TabIsPinned = false
Type = "CallStackPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Immediate"
TabWidth = 111.0
TabIsPinned = false
Type = "ImmediatePanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Output"
TabWidth = 90.0
TabIsPinned = false
Type = "OutputPanel"

[[Breakpoints]]
File = "src\\BeefGenerator.bf"
Line = 248
Column = 2

[[Breakpoints]]
File = "src\\FileUtils.bf"
Line = 7
Column = 2

[[BookmarkFolders]]
Title = ""

[OutputFilters]
ModuleLoadMessages = false
ModuleUnloadMessages = false
ProcessExitMessages = false
ThreadCreateMessages = false
ThreadExitMessages = false
SymbolLoadMessages = false
ProgramOutput = false
