FileVersion = 1
LastConfig = "Debug"
LastPlatform = "Win64"
RecentFilesList = ["src\\CParser.bf", "c:\\Program Files\\BeefLang\\BeefLibs\\corlib\\src\\Variant.bf", "c:\\Program Files\\BeefLang\\BeefLibs\\corlib\\src\\String.bf", "src\\Program.bf", "src\\Extensions.bf"]

[MainWindow]
X = 2713
Y = 208
Width = 625
Height = 587
ShowKind = "ShowMaximized"

[MainDockingFrame]
Type = "DockingFrame"
SplitType = 2

[[MainDockingFrame.DockedWidgets]]
RequestedWidth = 350.0
RequestedHeight = 200.0
SizePriority = 200.0
Type = "DockingFrame"
SplitType = 1

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
RequestedWidth = 200.0
RequestedHeight = 200.0
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Workspace"
TabWidth = 115.0
TabIsPinned = false
Type = "ProjectPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
IsFillWidget = true
Permanent = true
RequestedWidth = 150.0
RequestedHeight = 150.0
SizePriority = 150.0
DefaultDocumentsTabbedView = true
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "String.bf"
TabWidth = 89.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "c:\\Program Files\\BeefLang\\BeefLibs\\corlib\\src\\String.bf"
CursorPos = 95964
VertPos = 98394.0
ProjectName = "corlib"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "CParser.bf"
TabWidth = 99.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\CParser.bf"
CursorPos = 2810
VertPos = 2290.0
ProjectName = "HushBindingGen"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Extensions.bf"
TabWidth = 116.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Extensions.bf"
CursorPos = 247
VertPos = 736.0
ProjectName = "HushBindingGen"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Program.bf"
TabWidth = 106.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Program.bf"
CursorPos = 340
ProjectName = "HushBindingGen"

[[MainDockingFrame.DockedWidgets]]
RequestedWidth = 250.0
RequestedHeight = 254.0
Type = "DockingFrame"
SplitType = 1

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
RequestedWidth = 250.0
RequestedHeight = 250.0
SizePriority = 1272.0
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Memory"
TabWidth = 99.0
TabIsPinned = false
Type = "MemoryPanel"
AutoResize = "Auto_Mul8"
RequestedWidth = 300.0

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Watch"
TabWidth = 86.0
TabIsPinned = false
Type = "WatchPanel"
Columns = [{Width = 200.0}, {Width = 200.0}, {Width = 200.0}]

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs.Items]]
EvalStr = ""

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Auto"
TabWidth = 77.0
TabIsPinned = false
Type = "AutoWatchPanel"
Columns = [{Width = 200.0}, {Width = 200.0}, {Width = 200.0}]

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
RequestedWidth = 250.0
RequestedHeight = 250.0
SizePriority = 1272.0
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Threads"
TabWidth = 97.0
TabIsPinned = false
Type = "ThreadPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Call Stack"
TabWidth = 105.0
TabIsPinned = false
Type = "CallStackPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Immediate"
TabWidth = 111.0
TabIsPinned = false
Type = "ImmediatePanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Output"
TabWidth = 90.0
TabIsPinned = false
Type = "OutputPanel"

[[BookmarkFolders]]
Title = ""

[OutputFilters]
ModuleLoadMessages = false
ModuleUnloadMessages = false
ProcessExitMessages = false
ThreadCreateMessages = false
ThreadExitMessages = false
SymbolLoadMessages = false
ProgramOutput = false
